name: 'release'
on:
  push:
    branches:
      - release

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Install dependencies and build
        run: pnpm i && pnpm build

      - name: Get Previous Tag
        id: previous_tag
        uses: 'WyriHaximus/github-action-get-previous-tag@v1'
        with:
          fallback: 0.0.0

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
          tag_name: ${{steps.previous_tag.outputs.tag}}
